steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - pull
      - asia-southeast1-docker.pkg.dev/$PROJECT_ID/maria-containers/maria-latentsync:job-candidate
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --cache-from
      - asia-southeast1-docker.pkg.dev/$PROJECT_ID/maria-containers/maria-latentsync:job-candidate
      - --file
      - services/latentsync/Dockerfile
      - --tag
      - asia-southeast1-docker.pkg.dev/$PROJECT_ID/maria-containers/maria-latentsync:job-candidate
      - .
images:
  - asia-southeast1-docker.pkg.dev/$PROJECT_ID/maria-containers/maria-latentsync:job-candidate
options:
  machineType: E2_HIGHCPU_8
  diskSizeGb: 200
timeout: 3600s
